# Dependencies
markdown:         kramdown
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            New Wave Nigeria
tagline:          ''
description:      'Add description here...'
url:              http://hyde.getpoole.com
baseurl:          http://newwavenigeria.github.io/poole/

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde

# Plugins
plugins:
  - jekyll-paginate

# Gems
gems: [jekyll-paginate]
