# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            New Wave Nigeria
tagline:          ''
description:      'A nonprofit organization geared towards the amelioration of Nigeria and the quality of life for all therein'
url:              https://newwavenigeria.github.io/
baseurl:          https://newwavenigeria.github.io/

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde

# Plugins
plugins:
  - jekyll-paginate

# Gems
gems: [jekyll-paginate]
